version: '3.8'

services:
  # Aplicação React
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: tvdoutor-ads-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - tvdoutor-network

  # Serviço de desenvolvimento (opcional)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    container_name: tvdoutor-ads-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - tvdoutor-network
    profiles:
      - dev

  # Nginx reverso (opcional, para produção)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    container_name: tvdoutor-ads-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - tvdoutor-network
    profiles:
      - production

networks:
  tvdoutor-network:
    driver: bridge

volumes:
  app-data:
