// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { validateEnvironment } from '@/config/production';

// Simplified Database type to resolve build issues
type Database = any;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validar variáveis de ambiente
if (!validateEnvironment()) {
  console.error('🚨 Erro de Configuração: Variáveis de ambiente do Supabase não configuradas');
  console.error('📋 Para corrigir:');
  console.error('   1. Acesse o dashboard da Vercel');
  console.error('   2. Vá em Settings → Environment Variables');
  console.error('   3. Adicione VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY');
  console.error('   4. Faça redeploy do projeto');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  realtime: {
    timeout: 30000, // 30 segundos de timeout
    heartbeatIntervalMs: 30000, // Heartbeat a cada 30 segundos
    reconnectAfterMs: (tries) => Math.min(tries * 1000, 30000), // Reconexão progressiva
    params: {
      eventsPerSecond: 10 // Rate limit realtime events
    }
  },
  global: {
    headers: {
      'X-Client-Info': 'tvdoutor-ads-web'
    }
  }
});