// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Simplified Database type to resolve build issues
type Database = any;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce' // Use PKCE flow for enhanced security
  },
  global: {
    headers: {
      'X-Client-Info': 'tvdoutor-ads-web'
    }
  },
  realtime: {
    params: {
      eventsPerSecond: 10 // Rate limit realtime events
    }
  }
});